#!/bin/bash

echo "Making a movie!"
# python input_files/get_rho_fluc.py
python input_files/get_steady_rho.py
for t_max in 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150
do
	echo $t_max
  sed -i '' "s/^inline constexpr double t_max.*/inline constexpr double t_max \{${t_max}\}\; \/\/Runtime (in Myr)/" user_inputs.h
  sed -i '' "s/^inline constexpr char spec_output\[\].*/inline constexpr char spec_output\[\] \{ \"output_files\/spectrum_hydro_${t_max}myr\.txt\"\}\;/" user_inputs.h
  sed -i '' "s/^inline constexpr char gas_output\[\].*/inline constexpr char gas_output\[\] \{ \"output_files\/gas_test_hydro_${t_max}myr\.txt\"\}\;/" user_inputs.h
  sed -i '' "s/^inline constexpr char otf_output\[\].*/inline constexpr char otf_output\[\] \{ \"output_files\/otf_test_hydro_${t_max}myr\.txt\"\}\;/" user_inputs.h
  sed -i '' "s/^inline constexpr char otf_output_bayu\[\].*/inline constexpr char otf_output_bayu\[\] \{ \"output_files\/otf_bayu_${t_max}myr\.txt\"\}\; \/\/added 21\/12\/10/" user_inputs.h
  make clean
  make
  ./1d_radtransfer.x
done

cp output_files/spectrum_hydro_* output_files/may24/
cp output_files/otf_bayu_* output_files/may24/
cp output_files/gas_test_hydro_* output_files/may24/
